// <auto-generated />
using System;
using Api.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Infrastructure.Migrations
{
    [DbContext(typeof(SpotifyAppContext))]
    [Migration("20190214151843_CurrentTrackExpectedFinishTime")]
    partial class CurrentTrackExpectedFinishTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Api.Domain.Entities.Party", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Playback");

                    b.HasKey("Id");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("Api.Domain.Entities.QueueItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddedByUserId");

                    b.Property<string>("Artist");

                    b.Property<long>("DurationMillis");

                    b.Property<string>("ForPartyId");

                    b.Property<int>("Index");

                    b.Property<string>("SpotifyUri");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("ForPartyId");

                    b.ToTable("QueueItems");
                });

            modelBuilder.Entity("Api.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CurrentPartyId");

                    b.Property<bool>("IsMember")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasComputedColumnSql("CAST(CASE WHEN CurrentPartyId IS NULL THEN 0 ELSE 1 END AS BIT)");

                    b.Property<bool>("IsOwner")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasComputedColumnSql("CAST(CASE WHEN OwnedPartyId IS NULL THEN 0 ELSE 1 END AS BIT)");

                    b.Property<bool>("IsPendingMember")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasComputedColumnSql("CAST(CASE WHEN PendingPartyId IS NULL THEN 0 ELSE 1 END AS BIT)");

                    b.Property<DateTime>("JoinedPartyDateTime");

                    b.Property<string>("OwnedPartyId");

                    b.Property<string>("PendingPartyId");

                    b.Property<string>("SpotifyAccessToken");

                    b.Property<string>("SpotifyRefreshToken");

                    b.Property<DateTime?>("SpotifyTokenExpiry");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPartyId");

                    b.HasIndex("OwnedPartyId")
                        .IsUnique()
                        .HasFilter("[OwnedPartyId] IS NOT NULL");

                    b.HasIndex("PendingPartyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.Domain.Entities.Party", b =>
                {
                    b.OwnsOne("Api.Domain.Entities.Track", "CurrentTrack", b1 =>
                        {
                            b1.Property<string>("PartyId");

                            b1.Property<string>("Artist");

                            b1.Property<int>("DurationMillis");

                            b1.Property<DateTime>("ExpectedFinishTime");

                            b1.Property<string>("Title");

                            b1.Property<string>("Uri");

                            b1.HasKey("PartyId");

                            b1.ToTable("Parties");

                            b1.HasOne("Api.Domain.Entities.Party")
                                .WithOne("CurrentTrack")
                                .HasForeignKey("Api.Domain.Entities.Track", "PartyId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.QueueItem", b =>
                {
                    b.HasOne("Api.Domain.Entities.User", "AddedByUser")
                        .WithMany("QueueItems")
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Domain.Entities.Party", "ForParty")
                        .WithMany("QueueItems")
                        .HasForeignKey("ForPartyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Api.Domain.Entities.User", b =>
                {
                    b.HasOne("Api.Domain.Entities.Party", "CurrentParty")
                        .WithMany("Members")
                        .HasForeignKey("CurrentPartyId");

                    b.HasOne("Api.Domain.Entities.Party", "OwnedParty")
                        .WithOne("Owner")
                        .HasForeignKey("Api.Domain.Entities.User", "OwnedPartyId");

                    b.HasOne("Api.Domain.Entities.Party", "PendingParty")
                        .WithMany("PendingMembers")
                        .HasForeignKey("PendingPartyId");

                    b.OwnsOne("Api.Domain.Entities.SpotifyDevice", "CurrentDevice", b1 =>
                        {
                            b1.Property<string>("UserId");

                            b1.Property<string>("DeviceId");

                            b1.Property<string>("Name");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.HasOne("Api.Domain.Entities.User")
                                .WithOne("CurrentDevice")
                                .HasForeignKey("Api.Domain.Entities.SpotifyDevice", "UserId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
